project:
  type: book
  resources:
    - "test.html"
book:
  title: "딥러닝 용어사전"
  author: "기여자 여러분"
  date: "2023. 7. 22."
  search: true
  repo-url: https://github.com/Pseudo-Lab/deep-learning-glossary
  repo-actions: [edit]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - part: glossary.qmd
      chapters:
        - markdown.qmd
        - register_edit.qmd
        - pr.qmd
    - contribution.qmd

format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt

website:
  google-analytics: "G-TFCJQ03RNB"
  page-footer:
    center: "by HuggingFace KREW"

